# default config for 1.3inch OLED HAT
buttons:
   upbutton: 6
   downbutton: 19
   leftbutton: 5
   rightbutton: 26
   okbutton: 21                 
   backbutton: 16
   offbutton: 13
display:
  #if you using i2c
  #i2c:
  #   address: 0x3C
  #   port: 1
  spi:
    device: 0
    port: 0
  
  #list of suported screens sh1106, ssd1306
  screen: sh1106
  #where 0 is no rotation, 1 is rotate 90° clockwise, 2 is 180° rotation and 3 represents 270° rotation.
  rotate: 2
fonts:
  - name: font 
    path: assets/fonts/PixelOperator.ttf
    size: 16
  - name: fontsmallbold 
    path: assets/fonts/PixelOperator-Bold.ttf
    size: 8
  - name: fontbold
    path: assets/fonts/PixelOperator-Bold.ttf
    size: 16
  - name: fontsmall
    path: assets/fonts/PixelOperator.ttf
    size: 8
bitmaps:
  - name: scrollicon
    path: assets/icons/scroll.png

  - name: snakeicon
    path: assets/icons/snake.png

  - name: outlineicon
    path: assets/icons/outline.png

  - name: mp3icon
    path: assets/icons/mp3.png

  - name: legacyappsicon
    path: assets/icons/legacyapps.png

  - name: wifiicon
    path: assets/icons/wifi.png

  - name: countericon
    path: assets/icons/counter.png
  
  - name: boxicon
    path: assets/icons/box.png

  - name: usbicon
    path: assets/icons/usb.png

  - name: settingsicon
    path: assets/icons/settings.png